# Generated by Django 5.0.4 on 2024-04-23 00:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
                ("social_email", models.CharField(blank=True, max_length=200)),
                ("social_github", models.CharField(blank=True, max_length=200)),
                ("social_facebook", models.CharField(blank=True, max_length=200)),
                ("social_linkedin", models.CharField(blank=True, max_length=200)),
                ("social_instagram", models.CharField(blank=True, max_length=200)),
                ("social_website", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("snippet", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "post_img",
                    models.ImageField(blank=True, null=True, upload_to="post/"),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="posts.author"
                    ),
                ),
            ],
        ),
    ]
