# Generated by Django 5.0.4 on 2024-05-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review",
            field=models.TextField(),
        ),
    ]
