# Generated by Django 5.0.4 on 2024-04-27 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "profile_pic",
                    models.ImageField(
                        default="profile/avatar.jpg", upload_to="profile/"
                    ),
                ),
                (
                    "social_email",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "social_github",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "social_facebook",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "social_linkedin",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "social_instagram",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "social_portfolio",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "social_digital_resume",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
